version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
      - PORT=${PORT:-8000}
    volumes:
      - db-data:/app/prisma
    depends_on:
      - db-migration
    restart: always

  db-migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pnpm prisma migrate deploy && pnpm prisma generate"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - db-data:/app/prisma
      
volumes:
  db-data:
